name: Parallel execuation End-to-end tests
on:
 push:
   branches:
     - main
jobs:
 Cypress-addTocart-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2

       #Install npm dependencies, cache them correctly 
       # and run all cypress tests

     - name: Cypress run 
       uses: cypress-io/github-action@v5 
       with : 
        browser : chrome
        command : npm run test:addToCart

 register-flow-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2

       #Install npm dependencies, cache them correctly 
       # and run all cypress tests

     - name: Cypress run 
       uses: cypress-io/github-action@v5 
       with : 
        browser : chrome
        command : npm run test:registerflow
